import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getCurrentUser } from '@/lib/session'

export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const reportId = searchParams.get('reportId')
    const format = searchParams.get('format') || 'CSV'
    const type = searchParams.get('type') || 'DAILY'

    if (reportId) {
      const report = await db.report.findUnique({
        where: { id: reportId },
        include: { User: { select: { name: true } } }
      })

      if (!report) {
        return NextResponse.json({ error: 'Report not found' }, { status: 404 })
      }

      const data = JSON.parse(report.data)

      if (format === 'CSV') {
        const csv = generateCSV(data, type)
        return new NextResponse(csv, {
          headers: {
            'Content-Type': 'text/csv',
            'Content-Disposition': `attachment; filename="${report.title.replace(/[^a-z0-9]/gi, '_')}.csv"`
          }
        })
      }

      const pdfContent = generatePDFContent(report, data)
      return new NextResponse(pdfContent, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="${report.title.replace(/[^a-z0-9]/gi, '_')}.html"`
        }
      })
    }

    // Generate a new report on the fly
    let data: object
    switch (type) {
      case 'WEEKLY':
        data = await generateWeeklyReport()
        break
      case 'MONTHLY':
        data = await generateMonthlyReport()
        break
      case 'DAILY':
      default:
        data = await generateDailyReport()
        break
    }

    if (format === 'CSV') {
      const csv = generateCSV(data, type)
      return new NextResponse(csv, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="${type.toLowerCase()}_report_${new Date().toISOString().split('T')[0]}.csv"`
        }
      })
    }

    const htmlContent = generatePDFContent({
      title: `${type.charAt(0) + type.slice(1).toLowerCase()} Report`,
      type,
      createdAt: new Date(),
      User: { name: user.name || user.email }
    }, data)

    return new NextResponse(htmlContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="${type.toLowerCase()}_report_${new Date().toISOString().split('T')[0]}.html"`
      }
    })
  } catch {
    return NextResponse.json({ error: 'Failed to export report' }, { status: 500 })
  }
}

function generateCSV(data: object, type: string): string {
  const rows: string[] = []
  rows.push(`${type} Report - Generated: ${new Date().toISOString()}`)
  rows.push('')
  
  if (Array.isArray(data)) {
    if (data.length > 0) {
      const headers = Object.keys(data[0] as Record<string, unknown>)
      rows.push(headers.join(','))
      data.forEach(item => {
        const values = Object.values(item as Record<string, unknown>).map(v => 
          typeof v === 'string' ? `"${v}"` : v
        )
        rows.push(values.join(','))
      })
    }
  } else {
    const obj = data as Record<string, unknown>
    Object.entries(obj).forEach(([key, value]) => {
      if (typeof value === 'object' && !Array.isArray(value)) {
        rows.push(`${key}`)
        Object.entries(value as Record<string, unknown>).forEach(([k, v]) => {
          rows.push(`  ${k},${v}`)
        })
      } else {
        rows.push(`${key},${value}`)
      }
    })
  }
  
  return rows.join('\n')
}

function generatePDFContent(report: { title: string; type: string; createdAt: Date; User: { name: string } }, data: object): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <title>${report.title}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; }
    h1 { color: #333; }
    .meta { color: #666; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f4f4f4; }
  </style>
</head>
<body>
  <h1>${report.title}</h1>
  <div class="meta">
    <p>Type: ${report.type}</p>
    <p>Generated: ${new Date(report.createdAt).toLocaleString()}</p>
    <p>Generated by: ${report.User.name}</p>
  </div>
  <div class="content">
    <pre>${JSON.stringify(data, null, 2)}</pre>
  </div>
</body>
</html>
  `
}

async function generateDailyReport() {
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  const newPlayers = await db.player.count({
    where: { createdAt: { gte: today } }
  })

  const purchases = await db.purchase.findMany({
    where: { createdAt: { gte: today }, status: 'COMPLETED' }
  })

  const revenue = purchases.reduce((sum, p) => sum + p.amount, 0)

  const newBugs = await db.bugReport.count({
    where: { createdAt: { gte: today } }
  })

  const resolvedBugs = await db.bugReport.count({
    where: { updatedAt: { gte: today }, status: 'RESOLVED' }
  })

  return {
    date: today.toISOString().split('T')[0],
    newPlayers,
    totalPurchases: purchases.length,
    revenue,
    newBugs,
    resolvedBugs
  }
}

async function generateWeeklyReport() {
  const weekAgo = new Date()
  weekAgo.setDate(weekAgo.getDate() - 7)

  const newPlayers = await db.player.count({
    where: { createdAt: { gte: weekAgo } }
  })

  const purchases = await db.purchase.findMany({
    where: { createdAt: { gte: weekAgo }, status: 'COMPLETED' }
  })

  const revenue = purchases.reduce((sum, p) => sum + p.amount, 0)

  const newBugs = await db.bugReport.count({
    where: { createdAt: { gte: weekAgo } }
  })

  const resolvedBugs = await db.bugReport.count({
    where: { updatedAt: { gte: weekAgo }, status: 'RESOLVED' }
  })

  const playersByStatus = await db.player.groupBy({
    by: ['status'],
    _count: { id: true }
  })

  return {
    period: `${weekAgo.toISOString().split('T')[0]} - ${new Date().toISOString().split('T')[0]}`,
    newPlayers,
    totalPurchases: purchases.length,
    revenue,
    newBugs,
    resolvedBugs,
    playersByStatus
  }
}

async function generateMonthlyReport() {
  const monthAgo = new Date()
  monthAgo.setDate(monthAgo.getDate() - 30)

  const newPlayers = await db.player.count({
    where: { createdAt: { gte: monthAgo } }
  })

  const purchases = await db.purchase.findMany({
    where: { createdAt: { gte: monthAgo }, status: 'COMPLETED' }
  })

  const revenue = purchases.reduce((sum, p) => sum + p.amount, 0)

  const purchasesByType = await db.purchase.groupBy({
    by: ['itemType'],
    _count: { id: true },
    _sum: { amount: true },
    where: { createdAt: { gte: monthAgo }, status: 'COMPLETED' }
  })

  const bugsBySeverity = await db.bugReport.groupBy({
    by: ['severity'],
    _count: { id: true }
  })

  const games = await db.game.findMany({
    select: { title: true, playerCount: true, status: true }
  })

  return {
    period: `${monthAgo.toISOString().split('T')[0]} - ${new Date().toISOString().split('T')[0]}`,
    newPlayers,
    totalPurchases: purchases.length,
    revenue,
    purchasesByType,
    bugsBySeverity,
    games
  }
}
